name: Closed Reference Notifier
description:
  GitHub action that opens an issue when a in-code refered issue/pull request is
  closed
inputs:
  token:
    description: secrets.GITHUB_TOKEN
    required: true
  ignore:
    description: ignore directories, comma seperated list
    required: false
    default: .git
  issueLabels:
    description: the labels to create issues with, comma seperated list
    required: false
    default: closed reference
  issueLimit:
    description: the maximum number of issues to create
    required: false
    default: "5"
runs:
  using: composite
  steps:
    #    requires actions within actions as tracked in https://github.com/actions/runner/issues/646
    #    - uses: actions/setup-node@v2-beta
    #      with:
    #        node-version: '14'
    - run: node ${{ github.action_path }}/distAction/index.js
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_IGNORE: ${{ inputs.ignore }}
        INPUT_ISSUELABELS: ${{ inputs.issueLabels }}
        INPUT_ISSUELIMIT: ${{ inputs.issueLimit }}
branding:
  color: red
  icon: hash
