on:
  push:
    branches:
      - master

jobs:
  format-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - run: npm ci
      - name: Build bundles
        run: npm run build
      - name: Push build
        run: |
          git config --local user.email "zepatrik@users.noreply.github.com"
          git config --local user.name "zepatrik"
          git add distCli distAction
          git commit -a -m "autogen: build bundles" && git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master || true
